# Generated by Django 5.1 on 2024-08-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
